#pragma once

#define BUILD_CONFIG_UNKNOWN 0
#define BUILD_CONFIG_DEBUG   1
#define BUILD_CONFIG_RELEASE 2
#define BUILD_CONFIG_DIST    3

#define BUILD_SYSTEM_UNKNOWN     0
#define BUILD_SYSTEM_WINDOWS     1
#define BUILD_SYSTEM_XBOX        2
#define BUILD_SYSTEM_MACOSX      3
#define BUILD_SYSTEM_IOS         4
#define BUILD_SYSTEM_LINUX       5
#define BUILD_SYSTEM_ANDROID     6
#define BUILD_SYSTEM_PLAYSTATION 7

#define BUILD_TOOLSET_UNKNOWN 0
#define BUILD_TOOLSET_MSVC    1
#define BUILD_TOOLSET_CLANG   2
#define BUILD_TOOLSET_GCC     3

#define BUILD_PLATFORM_UNKNOWN 0
#define BUILD_PLATFORM_X86     1
#define BUILD_PLATFORM_AMD64   2
#define BUILD_PLATFORM_ARM32   3
#define BUILD_PLATFORM_ARM64   4

#define BUILD_IS_CONFIG_DEBUG ((BUILD_CONFIG == BUILD_CONFIG_DEBUG) || (BUILD_CONFIG == BUILD_CONFIG_RELEASE))
#define BUILD_IS_CONFIG_DIST  ((BUILD_CONFIG == BUILD_CONFIG_RELEASE) || (BUILD_CONFIG == BUILD_CONFIG_DIST))

#define BUILD_IS_SYSTEM_UNIX        ((BUILD_SYSTEM == BUILD_SYSTEM_MACOSX) || (BUILD_SYSTEM == BUILD_SYSTEM_IOS) || (BUILD_SYSTEM == BUILD_SYSTEM_LINUX) || (BUILD_SYSTEM == BUILD_SYSTEM_ANDROID))
#define BUILD_IS_SYSTEM_APPLE       ((BUILD_SYSTEM == BUILD_SYSTEM_MACOSX) || (BUILD_SYSTEM == BUILD_SYSTEM_IOS))
#define BUILD_IS_SYSTEM_MICROSOFT   (BUILD_SYSTEM == BUILD_SYSTEM_WINDOWS)
#define BUILD_IS_SYSTEM_SONY        (BUILD_SYSTEM == BUILD_SYSTEM_PLAYSTATION)
#define BUILD_IS_SYSTEM_WINDOWS     (BUILD_SYSTEM == BUILD_SYSTEM_WINDOWS)
#define BUILD_IS_SYSTEM_XBOX        (BUILD_SYSTEM == BUILD_SYSTEM_XBOX)
#define BUILD_IS_SYSTEM_MACOSX      (BUILD_SYSTEM == BUILD_SYSTEM_MACOSX)
#define BUILD_IS_SYSTEM_IOS         (BUILD_SYSTEM == BUILD_SYSTEM_IOS)
#define BUILD_IS_SYSTEM_LINUX       (BUILD_SYSTEM == BUILD_SYSTEM_LINUX)
#define BUILD_IS_SYSTEM_ANDROID     (BUILD_SYSTEM == BUILD_SYSTEM_ANDROID)
#define BUILD_IS_SYSTEM_PLAYSTATION (BUILD_SYSTEM == BUILD_SYSTEM_PLAYSTATION)

#define BUILD_IS_TOOLSET_MSVC  (BUILD_TOOLSET == BUILD_TOOLSET_MSVC)
#define BUILD_IS_TOOLSET_CLANG (BUILD_TOOLSET == BUILD_TOOLSET_CLANG)
#define BUILD_IS_TOOLSET_GCC   (BUILD_TOOLSET == BUILD_TOOLSET_GCC)

#define BUILD_IS_PLATFORM_X86   (BUILD_PLATFORM == BUILD_PLATFORM_X86)
#define BUILD_IS_PLATFORM_AMD64 (BUILD_PLATFORM == BUILD_PLATFORM_AMD64)
#define BUILD_IS_PLATFORM_ARM32 (BUILD_PLATFORM == BUILD_PLATFORM_ARM32)
#define BUILD_IS_PLATFORM_ARM64 (BUILD_PLATFORM == BUILD_PLATFORM_ARM64)